import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './style/globals.css'
import Axios from 'axios'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  Axios.defaults.baseURL = process.env.NEXT_PUBLIC_SERVER_BASE_URL + "/api";
  Axios.defaults.withCredentials = true;
  
  return (
    <html lang="en">
      <body className={inter.className}>{children}</body>
    </html>
  )
}
